name: dashkiosk-image-config
version: '0.1'
summary: Basic configuration for a dashkiosk appliance server
description: |
  This snap carries out basic configuration for an UbuntuCore appliance
  image. It sets the default hostname and avahi name, looks up the
  correct timezone via geoip and provides a daemon that auto-imports
  a netplan.yaml file from USB key to set up a WLAN connetion
  if desired.


grade: stable
confinement: strict

apps:
  set-name:
    command: bin/set-name
    daemon: simple
    plugs:
      - hostname-control
      - avahi-observe
      - avahi-control
  set-timezone:
    command: bin/set-timezone
    daemon: simple
    plugs:
      - network
      - network-bind
      - timezone-control
  netplan-import:
    command: bin/netplan-import
    daemon: simple
    plugs:
      - system-observe
      - hardware-observe
      - mount-observe
      - network-setup-control
      - removable-media
      - shutdown
      - udisks2

parts:
  config:
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av set-name $SNAPCRAFT_PART_INSTALL/bin/
      cp -av set-timezone $SNAPCRAFT_PART_INSTALL/bin/
      cp -av netplan-import $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - netcat-openbsd
      - avahi-utils
      - udisks2
      - wget
