name: dashkiosk-image-config
version: '0.1'
summary: Basic configuration for a dashkiosk appliance server
description: |
  This snap carries basic configuration for a dashkiosk based appliance
  server image.

grade: stable
confinement: strict
apps:
  setup:
    command: bin/setup.sh
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - network-setup-control
      - timezone-control

hooks:
  configure:
    plugs:
      - hostname-control
      - avahi-observe
      - avahi-control

parts:
  config:
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av setup.sh $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - netcat-openbsd
      - avahi-utils
